[package]
edition = "2021"
name = "w3registrar"
version = "0.1.0"

[dependencies]
anyhow = "1.0.79"
futures = "0.3.30"
matrix-sdk = "0.7.1"
serde = { version = "1.0.195", features = ["derive"] }
serde_json = "1.0.111"
subxt = { version = "0.37.0", features = ["substrate-compat"] }
subxt-signer = "0.37.0"
tokio = { version = "1.35.1", features = ["full"] }
toml = "0.8.8"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }

[dev-dependencies]
mockall = "0.13.0"
tokio-test = "0.4.3"

[[bin]]
name = "challenger"
path = "src/bin/challenger.rs"

[[bin]]
name = "watcher"
path = "src/bin/watcher.rs"
