# Logging configuration
log_level = "info"

# Matrix configuration
[matrix]
homeserver = "https://matrix.org"
username = "regbot"
password = "abc123"
security_key = "EfT0 1WXL nIi8 v1Zx 15c8 B8Ux bKdS fLUZ 5uVk zje7 KYFj ZiLf"
admins = [
    "@sara:matrix.org",
    "@bill:matrix.org",
]

# IdentityChain configuration
[watcher]
endpoint = "wss://dev.rotko.net/rococo-people"
registrar_index = 0
keystore_path = "/path/to/your/keystore"
