services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: ${BUILD_TARGET:-development}
    container_name: web
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - VITE_APP_WALLET_CONNECT_PROJECT_ID=${VITE_APP_WALLET_CONNECT_PROJECT_ID}
      - VITE_APP_DEFAULT_WS_URL=${VITE_APP_DEFAULT_WS_URL}
    ports:
      - "${PORT:-3000}:3000"
    env_file:
      - .env
