services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: ${BUILD_TARGET:-development}
    container_name: web
    ports:
      - "${PORT:-3000}:3000"
  web-nginx:
    image: nginx
    ports:
      - 127.0.0.1:63999:80
    restart: unless-stopped
    volumes:
      - ./dist/:/app:ro
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
