services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: ${BUILD_TARGET:-development}
    container_name: web
    ports:
      - "${PORT:-3000}:3000"
    env_file:
      - .env
