[package]
name = "watcher"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.208", features = ["derive"] }
anyhow = "1.0.86"
futures = "0.3.30"
tokio = { version = "1.39.2", features = ["full"] }
toml = "0.8.19"
tracing-subscriber = "0.3.18"
tracing = "0.1.40"
