name: Build and Deploy dev

env:
  NODE_VERSION: '18'
  GCP_PROJECT_ID: 'rbl-common'
  SERVER_USER: 'w3reg'
  SERVER_IP: '135.181.202.179'
  DEPLOY_PATH: '/home/w3reg/dev.w3reg.org'
  BUILD_TARGET: 'production'

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Build the Vite app
        env:
          BUILD_TARGET: 'production'
        run: |
          curl -fsSL https://bun.sh/install | bash -s "bun-canary"
          echo ${{ secrets.VITE_BUILD_ENV }} > .env
          echo BUILD_TARGET=${{ env.BUILD_TARGET }} docker compose up -d web
          BUILD_TARGET=${{ env.BUILD_TARGET }} docker compose up -d web
          docker compose cp web:/app/dist ./dist
          docker compose down
      
      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add SSH Key to Known Hosts
        run: |
          echo "$(ssh-keyscan -t rsa ${{ env.SERVER_IP }} 2>/dev/null)" >> ~/.ssh/known_hosts

      - name: Deploy to server
        run: |
          ssh ${{ env.SERVER_USER }}@${{ env.SERVER_IP }} "mkdir -p ${{ env.DEPLOY_PATH }}/w3registrar-www"
          scp -r ./dist ${{ env.SERVER_USER }}@${{ env.SERVER_IP }}:${{ env.DEPLOY_PATH }}/w3registrar-www
          ssh ${{ env.SERVER_USER }}@${{ env.SERVER_IP }} << EOF 
            cd ${{ env.DEPLOY_PATH }}/w3registrar-www
            pkill -f "bunx serve --single dist"
            screen -d -m ~/.bun/bin/bunx serve --single dist
          EOF

#jobs:
#  build-and-deploy:
#    runs-on: ubuntu-latest
#    environment: production
#    continue-on-error: true
#    steps:
